Remove call to configure logging
riptideio/pymodbus pull request #1106
Opened 2022-10-10 14:38 UTC by JonasNorling

This call configures logging for the whole process, not only the Pymodbus module, so it affects the application using this library.

2022-10-10 18:18 UTC, janiversen requested changes
It is true it affect the whole application, but removing it, is not a good solution since the removal makes it difficult for less experienced users to add logging.

I suppose packaging it as a function and documenting that would be a compromise.

2022-10-11 05:09 UTC, JonasNorling commented
I think that users, both less and more experienced, will more likely be surprised that their debug/info log messages disappear if they import pymodbus.constants. At least I was surprised by this — it is common for libraries to use the logger but they don't typically reconfigure it.

IMHO, it's not in the scope of pymodbus to provide functions for configuring logging when the standard logging facility is used. I agree that it would be a good idea to describe in the documentation how to get log messages out of pymodbus, if it's not already mentioned.

2022-10-11 05:28 UTC, tracernz commented
This is also listed as a pattern to avoid in the logging cookbook: https://docs.python.org/3/howto/logging-cookbook.html#adding-handlers-other-than-nullhandler-to-a-logger-in-a-library

2022-10-11 05:34 UTC, janiversen commented
You might be right with your arguments,  but the solution is not to remove the formatting, the information in the formatting is needed to debug modbus problems. I am open to merge a suggestion that do not remove logging.

The logging cookbook is example patterns not a law, if it was that bad pylint/flake8 would not allow it.

2022-10-11 05:37 UTC, tracernz commented
Indeed, and I must say the logging was very useful when taking first steps with pymodbus.

2022-10-17 17:44 UTC, mh-superbox commented
Setting `logging.basicConfig()` in `pymodbus.constants import defaults` causes me to get duplicate entries:

```
Python 3.10.4 (main, Jun 18 2022, 13:11:42) [GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logger = logging.getLogger("unipi-control")
>>> logger.setLevel(logging.DEBUG)
>>> handler = logging.StreamHandler()
>>> handler.setFormatter(logging.Formatter("%(levelname)s | %(message)s"))
>>> logger.addHandler(handler)
>>> logger.info("TEST")
INFO | TEST
>>> from pymodbus.client import AsyncModbusTcpClient
>>> logger.info("TEST")
INFO | TEST
19:44:24 INFO  <stdin>:1 TEST
```

2022-10-17 17:46 UTC, janiversen commented
See the conversation above.

2022-10-17 18:00 UTC, mh-superbox commented
> See the conversation above.

I have read the conversation. At the moment this does not change the fact that I get double entries and that this can't be r be overwritten.

2022-10-17 18:06 UTC, JonasNorling commented
Closing this PR so that someone else can suggest a solution. Opened bug #1119 instead.

2022-10-17 18:06 UTC, closed without merging