serial2TCP forwarding example
riptideio/pymodbus pull request #1116
Opened 2022-10-16 14:11 UTC by alexandrecuer

with :
- signal to stop gracefully
- asyncio.run() to make it easier for people who don't know much about asyncio

2022-10-16 14:15 UTC, janiversen commented
This looks good, I will review it soon. Would you like to add another PR that updates the general fowarder with your signal and async,run idea ?

2022-10-16 14:16 UTC, janiversen commented
Please solve the pylint error.

2022-10-16 18:56 UTC, janiversen commented
you can run the checks locally:
tox -e pylint
and
tox -e flake8

2022-10-16 19:05 UTC, janiversen commented
please do not suppress pylint messages ! they are there for a reason.

2022-10-16 19:43 UTC, alexandrecuer commented
I just left the `# pylint: disable=unused-argument` which is necessary for the graceful shutdown to work

if it is not acceptable, I will delete the pull request

2022-10-16 19:54 UTC, janiversen commented
> I just left the `# pylint: disable=unused-argument` which is necessary for the graceful shutdown to work
> 
> if it is not acceptable, I will delete the pull request

I have not done a review yet I am primarily waiting to CI to give green light, and I am not sure why you threaten to delete the PR !

unused-argument can easily be avoided and I hardly believe the graceful shutdown depends on a pylint disable !

That being said unused-argument is something we accept if there are a good reason to have it.

2022-10-16 20:02 UTC, janiversen requested changes
The code looks quite good, but there are a couple of formal issues.

2022-10-16 20:02 UTC, janiversen commented on examples/serial_forwarder.py
> +    parser = argparse.ArgumentParser(description="Command line options for examples")
I think you mean "for serial_forwarder", at least these options are not valid for most examples.

2022-10-16 20:02 UTC, janiversen commented on examples/serial_forwarder.py
> +    import asyncio
Please move this to the top with the other imports.

2022-10-16 20:09 UTC, alexandrecuer commented on examples/serial_forwarder.py
> +sudo python3 serial_forwarder.py --port "/dev/ttyUSB0" --baudrate 9600 --server_ip "192.168.1.27" --server_port=502 --slaves 1 2 3
To what i know, the default Modbus port number is 502

if you want to run on port 502, you need to use `sudo`

Ports below 1024 are restricted - only apps with root privileges can listen on those. I think this is the general rule on Linux/Unix

2022-10-16 20:12 UTC, janiversen commented on examples/serial_forwarder.py
> +sudo python3 serial_forwarder.py --port "/dev/ttyUSB0" --baudrate 9600 --server_ip "192.168.1.27" --server_port=502 --slaves 1 2 3
You are quite right depending on which system you are on. But independent you have already documented how to call it, so there are really no need to repeat it.

2022-10-16 20:39 UTC, alexandrecuer commented
> unused-argument can easily be avoided and I hardly believe the graceful shutdown depends on a pylint disable !
> 
> That being said unused-argument is something we accept if there are a good reason to have it.

I dont know a better and more appropriate way to do it but if you know one, I am interested

I have a similar problem when using click in some projects. Pylint is not happy and I have to add `# pylint: disable=no-value-for-parameter`

2022-10-17 16:27 UTC, janiversen approved these changes

2022-10-17 16:27 UTC, merged