Improve Docker Support
riptideio/pymodbus pull request #1145
Opened 2022-10-27 01:00 UTC by serroba

# What?

Improve docker support by adding a default working CMD instruction.

By default tries to run the modbus server in a headless mode.

Additionally, adding a bit more details to the documentation

# Why?

This makes the container more useful and friendly. It becomes ready to use with no much more to do.

# Proof it's working

<img width="843" alt="image" src="https://user-images.githubusercontent.com/1817347/198166463-35311050-07a5-4757-8f88-eed9fae3ddd1.png">

2022-10-27 01:06 UTC, serroba commented on Dockerfile
> +FROM python:3.9-slim-buster
this isn't particularly required, happy to keep in 3.8 if that's a preference

2022-10-27 14:10 UTC, janiversen requested changes

2022-10-27 14:10 UTC, janiversen commented on Dockerfile
> +RUN pip install -r requirements.txt && pip install -e .
I prefer to keep pip3, that way we do not get side effects if python2 is installed.

2022-10-27 19:37 UTC, serroba commented on Dockerfile
> +RUN pip install -r requirements.txt && pip install -e .
Sure I'll update. However, the scenario you are talking about it's not something that would happen accidentally.
Requires modify the dockerfile. However, I don't mind to revert the change

2022-10-30 11:28 UTC, janiversen approved these changes
LGTM.

2022-10-30 11:28 UTC, merged