SerialServer added handle_local_echo equivalent to SerialClient
riptideio/pymodbus pull request #1184
Opened 2022-11-10 15:13 UTC by gregorschatz

I'm working on a Device with not configurable echo on UART of RS485, and needed to implement an SerialServer, so I used 
```
from pymodbus.server import StartSerialServer
StartSerialServer(context=context, framer=ModbusRtuFramer, identity=identity,
                  port='/dev/ttymxc0', stopbits=1, bytesize=8, parity='N', 
                  timeout=.5, baudrate=9600,
                  handle_local_echo = True)
```
and added a new named parameter handle_local_echo like it already exists in ModbusSerialClient to solve the mass of conflikts in framing and parsing the own responses like new requests.

2022-11-10 15:57 UTC, janiversen commented
Please solve the CI errors, then I will review it.

2022-11-10 16:00 UTC, janiversen requested changes

2022-11-10 16:00 UTC, janiversen commented on pymodbus/server/async_io.py
> +        self.handle_local_echo = kwargs.get("handle_local_echo", Defaults.HandleLocalEcho) # handle_local_echo: bool = None ; handle_local_echo: bool = Defaults.HandleLocalEcho,
Please remove the comment it is confusing.

2022-11-10 16:00 UTC, janiversen commented on pymodbus/server/async_io.py
> +                # handle_local_echo=self.handle_local_echo,
What should this mean ?

2022-11-10 16:32 UTC, janiversen commented
Well I had a bit of time left, so wanted to give a hand with your errors, but you have not permitted that maintainers change the PR, so I cannot help you.

2022-11-11 10:35 UTC, janiversen commented
Closing this commits with committer id are moved to #1186, allowing us to modify the PR.

For future PRs please tick "allow maintainers to update", it makes life a lot simpler.

Thanks for the PR, it makes a lot of sense, hoping to see more PRs from your hand, and good luck with your device.

2022-11-11 10:35 UTC, closed without merging

2022-11-11 11:52 UTC, gregorschatz commented
Thanks and sorry , I haven't made many pull requests yet, next time I will check Allow edits and access to secrets by maintainers.

2022-11-11 11:55 UTC, janiversen commented
No problem, every beginning is difficult which is why we try to help. There are a lot to do in this project so feel free to submit more PRs, I am here if you need advice,
.