Support Python3.11
riptideio/pymodbus pull request #1246
Opened 2023-01-09 23:00 UTC by alexrudd2

Closes #1245.

All tests pass on Python3.11 the same as Python3.10 and 3.8 on MacOS for me.

I see you have simplified and cleaned up the CI a lot; awesome! Hopefully it's easy to add 3.11

2023-01-10 11:16 UTC, janiversen requested changes
Removing reuse_addr for UDP is a good thing, I thought I had done that already. BUT you cannot remove reuse_addr from TCP, this is highly needed.

2023-01-10 11:16 UTC, janiversen commented on examples/contrib/serial_forwarder.py
> +        self.server = ModbusTcpServer(context, address=(server_ip, server_port))
Please do not remove it from TCP it is needed. It is only removed from UDP.

2023-01-10 11:16 UTC, janiversen commented on examples/server_async.py
> -            allow_reuse_address=True,  # allow the reuse of an address
It is needed for TCP.

2023-01-10 11:16 UTC, janiversen commented on examples/server_async.py
> -            # TBD allow_reuse_address=True,  # allow the reuse of an address
Needed for TCP.

And all similar places, not UDP (I will not comment on the rest).

2023-01-10 11:16 UTC, janiversen commented on examples/server_async.py
> -            allow_reuse_address=True,  # allow the reuse of an address
Needed for TCP.

2023-01-10 12:24 UTC, janiversen commented
IMPORTANT, please do a "git pull" before making changes, I added a commit changing README.rst

2023-01-10 17:59 UTC, alexrudd2 commented
> Removing reuse_addr for UDP is a good thing, I thought I had done that already. 

You had set it to `False`, which now emits a DeprecationWarning in 3.11.

> BUT you cannot remove reuse_addr from TCP, this is highly needed.

OK, I assume TLS follows TCP.  Changed to only UDP.

> IMPORTANT, please do a "git pull" before making changes, I added a commit changing README.rst

OK.  I rebased and force-pushed.

2023-01-10 19:01 UTC, janiversen approved these changes
LGTM.

I wrote earlier "IMPORTANT, please do a "git pull" before making changes, I added a commit changing README.rst"

You did not do that, but instead did "git push -f" and thus killed my commit. It would have been nice, it you had included the change in your commit, so I avoided doing it twice.

2023-01-10 19:03 UTC, merged

2023-01-11 00:26 UTC, alexrudd2 commented
My apologies for not understanding your message, although I didn't ignore it.

 I saw you had committed 33659da, which merged `dev` into my branch.  (It's still available with `git log`)  I did not see any relevant README changes that weren't in other commits - the changes present would get dropped by merging this back into `dev`.  

I pulled `dev` and rebased this branch on top so there were no conflicts, then did `git push --force-with-lease`.  Using this instead of `--force` means I had was not overwriting any remote commits I had not seen. 

Had you encountered a merge conflict?  Did I make a mistake in the rebase?

2023-01-11 07:40 UTC, janiversen commented
I did a commit on this branch not dev. I did it directly on dev in the second turn.

I did not encounter a merge conflict my commit was simply gone, due to your “git push —force…” (any version of —force, replaces the commit log for the branch on the server with your version).

You should have done “git pull” before starting to work, then the normal “git push” would have worked. But anyhow it is history now and it was not a big problem, just wanted to mention it.

Looking forward to see more work from you. Let me know if you want ideas of what needs to be done.